server:
  port: 8010
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    non-secure-port: ${server.port}
    instance-id: AUTH-SERVER-${server.port}


management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

spring:
  application:
    name: account-server
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
          SQL: debug
          tool:
            hbm2ddl: trace
        springframework:
          web: DEBUG
        springframework.security: DEBUG
  lifecycle:
    timeout-per-shutdown-phase: 30s


jwt:
  secret: super-strong-secret-key-that-is-256-bits-long!
  expiration-time: 3600
  token-prefix: bearer
  header-string: Authorization
  login-url: /api/login
